services:

  sdr:
    image: ghcr.io/charlie-foxtrot/rtlsdr-airband:v5.0.12
    restart: always
    volumes:
      - ./rtl_airband.conf:/app/rtl_airband.conf
      - ./recordings:/recordings/
    devices:
      - /dev/bus/usb

  mongo:
    image: mongo:6.0.20-rc3
    restart: always
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: transcriber 
      MONGO_INITDB_ROOT_PASSWORD: transcriber
      MONGO_INITDB_DATABASE: transcriber
    ports:
      - 127.0.0.1:27017:27017

  python:
    image: python:3.11-slim
    volumes:
      - ./processor/app/:/usr/src/app
      - ./recordings/:/recordings
      - ./whisper-cache:/root/.cache/whisper
      - ./processor/requirements.txt:/requirements.txt
    entrypoint: sleep 2d
