{{- $uri := "" -}}
{{- if .Values.mongodb.enabled -}}
{{- $uri = printf "mongodb://root:%s@%s:27017/?authSource=admin" .Values.mongodb.auth.rootPassword (include "wavebrowser.mongodbHost" .) -}}
{{- else -}}
{{- $uri = required "externalMongodb.uri is required when mongodb.enabled is false" .Values.externalMongodb.uri -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wavebrowser.fullname" . }}-mongo
  labels:
    {{- include "wavebrowser.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_URI: {{ $uri | quote }}
