---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wavebrowser.fullname" . }}-recordings
  labels:
    {{- include "wavebrowser.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.recordings.accessMode | default "ReadWriteMany" }}
  {{- with .Values.recordings.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.recordings.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wavebrowser.fullname" . }}-model-cache
  labels:
    {{- include "wavebrowser.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.transcriber.modelCache.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.transcriber.modelCache.storage }}
