---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wavebrowser.fullname" . }}-sdr-config
  labels:
    {{- include "wavebrowser.labels" . | nindent 4 }}
data:
  rtl_airband.conf: |
    {{- .Values.sdr.config | nindent 4 }}
