---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wavebrowser.fullname" . }}-web
  labels:
    {{- include "wavebrowser.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.web.service.port }}
      targetPort: http
