---
apiVersion: v2
name: wavebrowser
description: SDR radio recording, transcription and web-frontend

type: application

version: 1.0.1
appVersion: 1.0.1

dependencies:
  - name: mongodb
    version: "~15.x"
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
